<a href="https://colab.research.google.com/github/itsShashankDev/Blog-website/blob/master/Exp1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np
import math as m
x1=input("enter any value of x1 ")
x2=input("enter any value of x2 ")
x3=input("enter any value of x3 ")
w1=input("enter the value of weight of x1 ")
w2=input("enter the value of weight of x2 ")
w3=input("enter the value of weight of x3 ")
b=input("enter the bias value")
w0=input("enter the weight to the bias")
u=float(x1)*float(w1)+float(x2)*float(x2)+float(x3)*float(w3)+float(b)*float(w0)
print("The Value of U :",u)
y=0.8/(1+m.exp(-2*u))
print("The Value of Output Y: ",y)

enter any value of x1 2
enter any value of x2 4
enter any value of x3 5
enter the value of weight of x1 2
enter the value of weight of x2 5
enter the value of weight of x3 8
enter the bias value6
enter the weight to the bias2
The Value of U : 72.0
The Value of Output Y:  0.8


In [3]:
import numpy as np
def sigmoid(x):
  return 1 / (1 + np.exp(-x))
n_input = int(input("enter any number of input : "))
n_hidden = int(input("enter any number of hidden layer : "))
n_output = int(input("enter any number of output : "))
input_data = np.random.randn(1, n_input)

weights_hidden = 0.01 * np.random.randn(n_input, n_hidden)
biases_hidden = np.zeros((1, n_hidden))
hidden_output = sigmoid(np.dot(input_data, weights_hidden) + biases_hidden)
weights_output = 0.01 * np.random.randn(n_hidden, n_output)
biases_output = np.zeros((1, n_output))
final_output = sigmoid(np.dot(hidden_output, weights_output) + biases_output)
print("Input Data:")
print(input_data)
print("\nHidden Layer Output:")
print(hidden_output)
print("\nFinal Output:")
print(final_output)

enter any number of input : 3
enter any number of hidden layer : 4
enter any number of output : 2
Input Data:
[[0.29222726 1.10443788 0.63769089]]

Hidden Layer Output:
[[0.50465668 0.50474138 0.50001524 0.49995284]]

Final Output:
[[0.49800811 0.49798676]]
