<a href="https://colab.research.google.com/github/itsShashankDev/Blog-website/blob/master/Exp2.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np
class Layer_Dense:
 def __init__(self, n_inputs, n_neurons):
  self.weights = 0.01 * np.random.randn(n_inputs, n_neurons)
  self.biases = np.zeros((1, n_neurons))
  self.output = None
  self.input = None
 def forward(self, inputs):
  self.input = inputs
  self.output = np.dot(inputs, self.weights) + self.biases
n_inputs = 4
n_neurons = 3
dense_layer = Layer_Dense(n_inputs, n_neurons)
input_data = np.random.randn(1, n_inputs)
dense_layer.forward(input_data)

print("Input:")
print(input_data)
print("\nWeights:")
print(dense_layer.weights)
print("\nBiases:")
print(dense_layer.biases)
print("\nOutput:")
print(dense_layer.output)


Input:
[[-0.5014639  -0.81317011 -1.03046993 -0.32978904]]

Weights:
[[-0.01121108 -0.00961257  0.0153594 ]
 [ 0.01479199  0.01316202 -0.00495307]
 [-0.00397652  0.00141553  0.00531889]
 [-0.00581754 -0.0088727   0.0003086 ]]

Biases:
[[0. 0. 0.]]

Output:
[[-0.0003902  -0.00441514 -0.00925722]]


In [ ]:
import numpy as np

class Layer_Dense:
    def __init__(self, n_inputs, n_neurons):

        self.weights = 0.1 * np.random.randn(n_inputs, n_neurons)
        self.biases = np.zeros((1, n_neurons))

    def forward(self, inputs):

        self.inputs = inputs
        self.output = np.dot(inputs, self.weights) + self.biases

class Activation_ReLU:
    def forward(self, inputs):
        self.output = np.maximum(0, inputs)


n_inputs = int(input("enter any number of input : "))
n_neurons = int(input("enter any number of neurons : "))


layer = Layer_Dense(n_inputs, n_neurons)
activation = Activation_ReLU()


inputs = np.random.randn(1, n_inputs)


layer.forward(inputs)


activation.forward(layer.output)


print("Output after ReLU activation:")
print(activation.output)


enter any number of input : 2
enter any number of neurons : 3
Output after ReLU activation:
[[0.         0.         0.03168423]]
