<a href="https://colab.research.google.com/github/itsShashankDev/Blog-website/blob/master/Exp7.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [4]:
import numpy as np
from scipy.signal import convolve2d

# Define the 8x8 image matrix
image_matrix = np.array([[1, 2, 3, 4, 5, 6, 7, 8],
                        [9, 10, 11, 12, 13, 14, 15, 16],
                        [17, 18, 19, 20, 21, 22, 23, 24],
                        [25, 26, 27, 28, 29, 30, 31, 32],
                        [33, 34, 35, 36, 37, 38, 39, 40],
                        [41, 42, 43, 44, 45, 46, 47, 48],
                        [49, 50, 51, 52, 53, 54, 55, 56],
                        [57, 58, 59, 60, 61, 62, 63, 64]])

# Define the 3x3 filter
filter_matrix = np.array([[1, 0, -1],
                          [1, 0, -1],
                          [1, 0, -1]])

# Compute the required padding size for "same" convolution
padding = filter_matrix.shape[0] // 2

# Apply zero padding to the image
padded_image = np.pad(image_matrix, padding, mode='constant', constant_values=0)

# Perform convolution
feature_map = convolve2d(padded_image, filter_matrix, mode='valid')

# Display the resulting feature map
print(feature_map)



[[  12    4    4    4    4    4    4  -22]
 [  30    6    6    6    6    6    6  -45]
 [  54    6    6    6    6    6    6  -69]
 [  78    6    6    6    6    6    6  -93]
 [ 102    6    6    6    6    6    6 -117]
 [ 126    6    6    6    6    6    6 -141]
 [ 150    6    6    6    6    6    6 -165]
 [ 108    4    4    4    4    4    4 -118]]


In [5]:
import numpy as np
from scipy.signal import convolve2d

# Define the 8x8 image matrix
image_matrix = np.array([[1, 2, 3, 4, 5, 6, 7, 8],
                        [9, 10, 11, 12, 13, 14, 15, 16],
                        [17, 18, 19, 20, 21, 22, 23, 24],
                        [25, 26, 27, 28, 29, 30, 31, 32],
                        [33, 34, 35, 36, 37, 38, 39, 40],
                        [41, 42, 43, 44, 45, 46, 47, 48],
                        [49, 50, 51, 52, 53, 54, 55, 56],
                        [57, 58, 59, 60, 61, 62, 63, 64]])

# Define the 3x3 filter
filter_matrix = np.array([[1, 0, -1],
                          [1, 0, -1],
                          [1, 0, -1]])

# Compute the required padding size for "same" convolution
padding = filter_matrix.shape[0] // 2

# Apply zero padding to the image
padded_image = np.pad(image_matrix, padding, mode='constant', constant_values=0)

# Perform convolution
feature_map = convolve2d(padded_image, filter_matrix, mode='valid')

# Display the resulting feature map
print(feature_map)


[[  12    4    4    4    4    4    4  -22]
 [  30    6    6    6    6    6    6  -45]
 [  54    6    6    6    6    6    6  -69]
 [  78    6    6    6    6    6    6  -93]
 [ 102    6    6    6    6    6    6 -117]
 [ 126    6    6    6    6    6    6 -141]
 [ 150    6    6    6    6    6    6 -165]
 [ 108    4    4    4    4    4    4 -118]]
