<a href="https://colab.research.google.com/github/itsShashankDev/Blog-website/blob/master/Exp8.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [5]:
import numpy as np
from scipy.signal import convolve2d
image_matrix = np.array([
[1, 2, 3, 4, 5, 6, 7, 8],
[9, 10, 11, 12, 13, 14, 15, 16],
[17, 18, 19, 20, 21, 22, 23, 24],
[25, 26, 27, 28, 29, 30, 31, 32],
[33, 34, 35, 36, 37, 38, 39, 40],
[41, 42, 43, 44, 45, 46, 47, 48],
[49, 50, 51, 52, 53, 54, 55, 56],
[57, 58, 59, 60, 61, 62, 63, 64]
])


filter_matrix = np.array([ [1, 0, -1],
[1, 0, -1],
[1, 0, -1]
])
padded_image = np.pad(image_matrix, ((1, 1), (1, 1)), mode='constant', constant_values=0)
feature_map = convolve2d(padded_image, filter_matrix, mode='valid')
relu_feature_map = np.maximum(0, feature_map)


print("\nPost-ReLU Feature Map:")

print(relu_feature_map)


filter_4x4 = np.array([ [1, 2, 3, 4],
[5, 6, 7, 8],
[9, 10, 11, 12],
[13, 14, 15, 16]
])
output_matrix_2x2 = convolve2d(relu_feature_map, filter_4x4, mode='valid')


print("\n4x4 Filter Matrix:")
print(filter_4x4)

print("\nOutput Matrix (2x2) after Convolution:")
print(output_matrix_2x2)


Post-ReLU Feature Map:
[[ 12   4   4   4   4   4   4   0]
 [ 30   6   6   6   6   6   6   0]
 [ 54   6   6   6   6   6   6   0]
 [ 78   6   6   6   6   6   6   0]
 [102   6   6   6   6   6   6   0]
 [126   6   6   6   6   6   6   0]
 [150   6   6   6   6   6   6   0]
 [108   4   4   4   4   4   4   0]]

4x4 Filter Matrix:
[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]
 [13 14 15 16]]

Output Matrix (2x2) after Convolution:
[[1788  700  700  700  558]
 [2736  816  816  816  648]
 [3696  816  816  816  648]
 [4656  816  816  816  648]
 [5340  796  796  796  630]]
